# Generated by Django 4.2.11 on 2024-05-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=50, verbose_name='County')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('month', models.CharField(max_length=10, verbose_name='Month')),
                ('week_day', models.IntegerField(verbose_name='Week Day')),
                ('day_number', models.IntegerField(verbose_name='Day Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('exact_time', models.TimeField(verbose_name='Time')),
            ],
        ),
    ]
