# Generated by Django 4.2.11 on 2024-05-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concerts',
            name='week_day',
            field=models.CharField(max_length=9, verbose_name='Week Day'),
        ),
    ]
